# Danh sách tỉnh/thành phố của Việt Nam
VIETNAM_CITIES = {
    "an giang": "An Giang",
    "bà rịa - vũng tàu": "Ba Ria - Vung Tau",
    "bắc giang": "Bac Giang",
    "bắc kạn": "Bac Kan",
    "bạc liêu": "Bac Lieu",
    "bắc ninh": "Bac Ninh",
    "bến tre": "Ben Tre",
    "bình định": "Binh Dinh",
    "bình dương": "Binh Duong",
    "bình phước": "Binh Phuoc",
    "bình thuận": "Binh Thuan",
    "cà mau": "Ca Mau",
    "cần thơ": "Can Tho",
    "cao bằng": "Cao Bang",
    "đà nẵng": "Da Nang",
    "đắk lắk": "Dak Lak",
    "đắk nông": "Dak Nong",
    "điện biên": "Dien Bien",
    "đồng nai": "Dong Nai",
    "đồng tháp": "Dong Thap",
    "gia lai": "Gia Lai",
    "hà giang": "Ha Giang",
    "hà nam": "Ha Nam",
    "hà nội": "Hanoi",
    "hà tĩnh": "Ha Tinh",
    "hải dương": "Hai Duong",
    "hải phòng": "Hai Phong",
    "hậu giang": "Hau Giang",
    "hòa bình": "Hoa Binh",
    "hưng yên": "Hung Yen",
    "khánh hòa": "Khanh Hoa",
    "kiên giang": "Kien Giang",
    "kon tum": "Kon Tum",
    "lai châu": "Lai Chau",
    "lâm đồng": "Lam Dong",
    "lạng sơn": "Lang Son",
    "lào cai": "Lao Cai",
    "long an": "Long An",
    "nam định": "Nam Dinh",
    "nghệ an": "Nghe An",
    "ninh bình": "Ninh Binh",
    "ninh thuận": "Ninh Thuan",
    "phú thọ": "Phu Tho",
    "phú yên": "Phu Yen",
    "quảng bình": "Quang Binh",
    "quảng nam": "Quang Nam",
    "quảng ngãi": "Quang Ngai",
    "quảng ninh": "Quang Ninh",
    "quảng trị": "Quang Tri",
    "sóc trăng": "Soc Trang",
    "sơn la": "Son La",
    "tây ninh": "Tay Ninh",
    "thái bình": "Thai Binh",
    "thái nguyên": "Thai Nguyen",
    "thanh hóa": "Thanh Hoa",
    "huế": "Hue",
    "tiền giang": "Tien Giang",
    "tphcm": "Ho Chi Minh",
    "sg": "Ho Chi Minh",
    "tp.hcm": "Ho Chi Minh",
    "trà vinh": "Tra Vinh",
    "tuyên quang": "Tuyen Quang",
    "vĩnh long": "Vinh Long",
    "vĩnh phúc": "Vinh Phuc",
    "yên bái": "Yen Bai"
}
# Danh sách tỉnh/thành phố của Việt Nam (viết tắt)