# weather_conditions_vi.py

# Từ điển dịch thuật cho mô tả thời tiết từ tiếng Anh sang tiếng Việt
WEATHER_CONDITIONS_VI = {
    "Sunny": "Nắng",
    "Clear": "Trời quang",
    "Partly cloudy": "Mây rải rác",
    "Cloudy": "Nhiều mây",
    "Overcast": "U ám",
    "Mist": "Sương mù",
    "Patchy rain possible": "Có thể có mưa rải rác",
    "Patchy snow possible": "Có thể có tuyết rải rác",
    "Patchy sleet possible": "Có thể có mưa tuyết rải rác",
    "Patchy freezing drizzle possible": "Có thể có mưa phùn đóng băng rải rác",
    "Thundery outbreaks possible": "Có thể có giông rải rác",
    "Blowing snow": "Tuyết thổi",
    "Blizzard": "Bão tuyết",
    "Fog": "Sương mù dày",
    "Freezing fog": "Sương mù đóng băng",
    "Patchy light drizzle": "Mưa phùn nhẹ rải rác",
    "Light drizzle": "Mưa phùn nhẹ",
    "Freezing drizzle": "Mưa phùn đóng băng",
    "Heavy freezing drizzle": "Mưa phùn đóng băng nặng",
    "Patchy light rain": "Mưa nhẹ rải rác",
    "Light rain": "Mưa nhẹ",
    "Moderate rain at times": "Mưa vừa phải từng lúc",
    "Moderate rain": "Mưa vừa",
    "Heavy rain at times": "Mưa lớn từng lúc",
    "Heavy rain": "Mưa lớn",
    "Light freezing rain": "Mưa đóng băng nhẹ",
    "Moderate or heavy freezing rain": "Mưa đóng băng vừa hoặc nặng",
    "Light sleet": "Mưa tuyết nhẹ",
    "Moderate or heavy sleet": "Mưa tuyết vừa hoặc nặng",
    "Patchy light snow": "Tuyết nhẹ rải rác",
    "Light snow": "Tuyết nhẹ",
    "Patchy moderate snow": "Tuyết vừa rải rác",
    "Moderate snow": "Tuyết vừa",
    "Patchy heavy snow": "Tuyết nặng rải rác",
    "Heavy snow": "Tuyết nặng",
    "Ice pellets": "Mưa đá nhỏ",
    "Light rain shower": "Mưa rào nhẹ",
    "Moderate or heavy rain shower": "Mưa rào vừa hoặc nặng",
    "Light snow showers": "Mưa tuyết nhẹ",
    "Moderate or heavy snow showers": "Mưa tuyết vừa hoặc nặng",
    "Light showers of ice pellets": "Mưa đá nhỏ nhẹ",
    "Moderate or heavy showers of ice pellets": "Mưa đá nhỏ vừa hoặc nặng",
    "Patchy light rain with thunder": "Mưa nhẹ rải rác kèm sấm",
    "Moderate or heavy rain with thunder": "Mưa vừa hoặc nặng kèm sấm",
    "Patchy light snow with thunder": "Tuyết nhẹ rải rác kèm sấm",
    "Moderate or heavy snow with thunder": "Tuyết vừa hoặc nặng kèm sấm",
    "Patchy rain nearby": "Mưa rải rác gần đó"
}